/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prova;
import prova.model.Livro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prova.DB.LivroArquivo;
/**
 *
 * @author laboratorio
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());
    
    private ArrayList<Livro> listaLivro = new ArrayList<>();
    private int indiceSelecionado = -1;

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        
        LivroArquivo arquivo = new LivroArquivo();
        
        listaLivro = arquivo.carregar();
        
        AtualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        btgSituacao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAnoPub = new javax.swing.JTextField();
        rdoFisico = new javax.swing.JRadioButton();
        rdoDigital = new javax.swing.JRadioButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        rdoNaoIniciado = new javax.swing.JRadioButton();
        rdoEmAndamento = new javax.swing.JRadioButton();
        rdoConcluido = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo: ");

        jLabel2.setText("Autor: ");

        jLabel3.setText("Ano de Publicação: ");

        jLabel4.setText("Tipo: ");

        jLabel5.setText("Categoria: ");

        jLabel6.setText("Situação de leitura: ");

        btgTipo.add(rdoFisico);
        rdoFisico.setText("Fisico");

        btgTipo.add(rdoDigital);
        rdoDigital.setText("Digital");

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Romance", "Ficção", "História" }));

        btgSituacao.add(rdoNaoIniciado);
        rdoNaoIniciado.setText("Não Iniciado");

        btgSituacao.add(rdoEmAndamento);
        rdoEmAndamento.setText("Em Andamento");

        btgSituacao.add(rdoConcluido);
        rdoConcluido.setText("Concluido");

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Ano de Pub.", "Tipo", "Categoria", "Sit. de Leitura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTabela);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(rdoFisico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rdoDigital))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAnoPub))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAutor))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoNaoIniciado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoEmAndamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoConcluido))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAnoPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoFisico)
                    .addComponent(rdoDigital))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdoNaoIniciado)
                    .addComponent(rdoEmAndamento)
                    .addComponent(rdoConcluido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void AtualizarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tblTabela.getModel();
        modelo.setRowCount(0);
        
        for(Livro livro : listaLivro){
            modelo.addRow(new Object[]{
                livro.getTitulo(),
                livro.getAutor(),
                livro.getAnoPub(),
                livro.getTipo(),
                livro.getCategoria(),
                livro.getSitLeitura()
            });
        }
    }
    
    
    private void LimparCampos(){
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAnoPub.setText("");
        
        rdoFisico.setSelected(false);
        rdoDigital.setSelected(false);
        
        
        rdoNaoIniciado.setSelected(false);
        rdoEmAndamento.setSelected(false);
        rdoConcluido.setSelected(false);
    }
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        String anoPub = txtAnoPub.getText();
        String categoria = (String) cmbCategoria.getSelectedItem();
        String tipo = "";
        String sitLeitura = "";
        
        if(rdoFisico.isSelected()){
            tipo = "Fisico";
        }else if(rdoDigital.isSelected()){
            tipo = "Digital";
        }
        
        if(rdoNaoIniciado.isSelected()){
            sitLeitura = "Nao Iniciado";
        }else if(rdoEmAndamento.isSelected()){
            sitLeitura = "Em Andamento";
        }else if(rdoConcluido.isSelected()){
            sitLeitura = "Concluido";
        }
        
        Livro livro = new Livro(
        titulo,
        autor,
        anoPub,
        categoria,
        tipo,
        sitLeitura
        );
        
        LivroArquivo arquivo = new LivroArquivo();
        arquivo.salvar(livro);
        
        
        listaLivro.add(livro);
        
        AtualizarTabela();
        LimparCampos();
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tblTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTabelaMouseClicked
        indiceSelecionado = tblTabela.getSelectedRow();
        
        if (indiceSelecionado == -1) {
        return;
        }
        
        Livro livro = listaLivro.get(indiceSelecionado);
        
        
        txtTitulo.setText(livro.getTitulo());
        txtAutor.setText(livro.getAutor());
        txtAnoPub.setText(livro.getAnoPub());
        
        if(livro.getTipo().equals("Fisico")){
            rdoFisico.setSelected(true);
            rdoDigital.setSelected(false);
        }else if(livro.getTipo().equals("Digital")){
            rdoFisico.setSelected(false);
            rdoDigital.setSelected(true);
        }
        
        if(livro.getSitLeitura().equals("Nao Iniciado")){
            rdoNaoIniciado.setSelected(true);
            rdoEmAndamento.setSelected(false);
            rdoConcluido.setSelected(false);
        }else if(livro.getSitLeitura().equals("Em Nadamneto")){
            rdoNaoIniciado.setSelected(false);
            rdoEmAndamento.setSelected(true);
            rdoConcluido.setSelected(false);
        }else if(livro.getSitLeitura().equals("Concluido")){
            rdoNaoIniciado.setSelected(false);
            rdoEmAndamento.setSelected(false);
            rdoConcluido.setSelected(true);
        }
    }//GEN-LAST:event_tblTabelaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     if (indiceSelecionado == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Selecione um livro na tabela."
        );
        return;
    }
     
     
        String tipo = "";
        String sitLeitura = "";
    
         if(rdoFisico.isSelected()){
            tipo = "Fisico";
        }else if(rdoDigital.isSelected()){
            tipo = "Digital";
        }
        
        if(rdoNaoIniciado.isSelected()){
            sitLeitura = "Nao Iniciado";
        }else if(rdoEmAndamento.isSelected()){
            sitLeitura = "Em Andamento";
        }else if(rdoConcluido.isSelected()){
            sitLeitura = "Concluido";
        }
        
        Livro livro = listaLivro.get(indiceSelecionado);
        
        livro.setAutor(txtAutor.getText());
        livro.setTitulo(txtTitulo.getText());
        livro.setAnoPub(txtAnoPub.getText());
        
        LivroArquivo arquivo = new LivroArquivo();
        arquivo.salvarTodos(listaLivro);
        
        AtualizarTabela();
        
         JOptionPane.showMessageDialog(
        this,
        "livro editado com sucesso!"
        );
    
     
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (indiceSelecionado == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Selecione um livro na tabela."
        );
        return;
        }
        
        listaLivro.remove(indiceSelecionado);
        LivroArquivo arquivo = new LivroArquivo();
        arquivo.salvarTodos(listaLivro);
        
        AtualizarTabela();

        LimparCampos();

        JOptionPane.showMessageDialog(
            this,
            "Livro excluído com sucesso!"
        );
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSituacao;
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoConcluido;
    private javax.swing.JRadioButton rdoDigital;
    private javax.swing.JRadioButton rdoEmAndamento;
    private javax.swing.JRadioButton rdoFisico;
    private javax.swing.JRadioButton rdoNaoIniciado;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtAnoPub;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
