/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicio4;
import exercicio4.DAO.AlunoArquivo;
import java.util.ArrayList;
import exercicio4.model.Aluno;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josep
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());
    private ArrayList<Aluno> listaAlunos = new ArrayList<>();
    private int indiceSelecionado = -1;

    
    
    private void LimparCampos() {

    TxtNome.setText("");
    FtxtDataNasc.setText("");
    TxtMatricula.setText("");
    TxtCurso.setText("");
    FtxtCpf.setText("");
    FtxtEndereco.setText("");
    FtxtTelefone.setText("");

    CboxMasc.setSelected(false);
    CboxFem.setSelected(false);

    jTable1.clearSelection();

    indiceSelecionado = -1;
    }
    
    private void AtualizarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        
        for(Aluno aluno : listaAlunos){
            modelo.addRow(new Object[]{
                aluno.getNome(),
                aluno.getMatricula(),
                aluno.getCurso(),
                aluno.getCpf(),
                aluno.getTelefone()
            });
        }
    }

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        
        AlunoArquivo arquivo = new AlunoArquivo();
        
        listaAlunos = arquivo.carregar();
        
        AtualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        FtxtDataNasc = new javax.swing.JFormattedTextField();
        TxtMatricula = new javax.swing.JTextField();
        FtxtCpf = new javax.swing.JFormattedTextField();
        FtxtEndereco = new javax.swing.JFormattedTextField();
        FtxtTelefone = new javax.swing.JFormattedTextField();
        TxtCurso = new javax.swing.JTextField();
        CboxMasc = new javax.swing.JCheckBox();
        CboxFem = new javax.swing.JCheckBox();
        BtnCadastrar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Data de Nascimento: ");

        jLabel3.setText("Matricula: ");

        jLabel4.setText("CPF: ");

        jLabel5.setText("Endereco: ");

        jLabel6.setText("Telefone: ");

        jLabel7.setText("Curso: ");

        jLabel8.setText("Sexo: ");

        FtxtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        FtxtDataNasc.setToolTipText("");

        try {
            FtxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            FtxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buttonGroup1.add(CboxMasc);
        CboxMasc.setText("Masculino");

        buttonGroup1.add(CboxFem);
        CboxFem.setText("Feminino");

        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(this::BtnCadastrarActionPerformed);

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(this::BtnEditarActionPerformed);

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(this::BtnExcluirActionPerformed);

        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(this::BtnLimparActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Matricula", "Curso", "CPF", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(CboxMasc)
                        .addGap(18, 18, 18)
                        .addComponent(CboxFem))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FtxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FtxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtCurso))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(FtxtTelefone))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(FtxtEndereco))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FtxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FtxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FtxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(FtxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CboxMasc)
                    .addComponent(CboxFem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar)
                    .addComponent(BtnEditar)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        String nome = TxtNome.getText();
        String dataNasc = FtxtDataNasc.getText();
        String curso = TxtCurso.getText();
        String cpf = FtxtCpf.getText();
        String endereco = FtxtEndereco.getText();
        String telefone = FtxtTelefone.getText();
        
        String matricula = TxtMatricula.getText();
        
        String sexo = "";
        
        if(CboxMasc.isSelected()){
            sexo = "Masculino";
        }else if(CboxFem.isSelected()){
            sexo = "Feminino";
        }
        
        Aluno aluno = new Aluno(
        nome,
        dataNasc,
        sexo,
        matricula,
        curso,
        cpf,
        endereco,
        telefone
    );
        
        AlunoArquivo arquivo = new AlunoArquivo();
        arquivo.salvar(aluno);
        
        listaAlunos.add(aluno);
        
        AtualizarTabela();
        LimparCampos();
           
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
         LimparCampos();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
     if (indiceSelecionado == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Selecione um aluno na tabela."
        );
        return;
    }

    String sexo = "";

    if (CboxMasc.isSelected()) {
        sexo = "Masculino";
    } else if (CboxFem.isSelected()) {
        sexo = "Feminino";
    }

    Aluno aluno = listaAlunos.get(indiceSelecionado);

    aluno.setNome(TxtNome.getText());
    aluno.setDataNascimento(FtxtDataNasc.getText());
    aluno.setSexo(sexo);
    aluno.setMatricula(TxtMatricula.getText());
    aluno.setCurso(TxtCurso.getText());
    aluno.setCpf(FtxtCpf.getText());
    aluno.setEndereco(FtxtEndereco.getText());
    aluno.setTelefone(FtxtTelefone.getText());

    AlunoArquivo arquivo = new AlunoArquivo();
    arquivo.salvarTodos(listaAlunos);
    
    AtualizarTabela();

    JOptionPane.showMessageDialog(
        this,
        "Aluno editado com sucesso!"
    );
    
    
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        indiceSelecionado = jTable1.getSelectedRow();
        
        if (indiceSelecionado == -1) {
        return;
        }
        
         Aluno aluno = listaAlunos.get(indiceSelecionado);

        TxtNome.setText(aluno.getNome());
        FtxtDataNasc.setText(aluno.getDataNascimento());
        TxtMatricula.setText(aluno.getMatricula());
        TxtCurso.setText(aluno.getCurso());
        FtxtCpf.setText(aluno.getCpf());
        FtxtEndereco.setText(aluno.getEndereco());
        FtxtTelefone.setText(aluno.getTelefone());

        if (aluno.getSexo().equals("Masculino")) {
            CboxMasc.setSelected(true);
            CboxFem.setSelected(false);
        } else if (aluno.getSexo().equals("Feminino")) {
            CboxMasc.setSelected(false);
            CboxFem.setSelected(true);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
            if (indiceSelecionado == -1) {
        JOptionPane.showMessageDialog(
            this,
            "Selecione um aluno na tabela."
        );
        return;
        }

        listaAlunos.remove(indiceSelecionado);

        AlunoArquivo arquivo = new AlunoArquivo();
        arquivo.salvarTodos(listaAlunos);
        
        AtualizarTabela();

        LimparCampos();

        JOptionPane.showMessageDialog(
            this,
            "Aluno excluído com sucesso!"
        );
    }//GEN-LAST:event_BtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JCheckBox CboxFem;
    private javax.swing.JCheckBox CboxMasc;
    private javax.swing.JFormattedTextField FtxtCpf;
    private javax.swing.JFormattedTextField FtxtDataNasc;
    private javax.swing.JFormattedTextField FtxtEndereco;
    private javax.swing.JFormattedTextField FtxtTelefone;
    private javax.swing.JTextField TxtCurso;
    private javax.swing.JTextField TxtMatricula;
    private javax.swing.JTextField TxtNome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
